### ISSUE TITLE
Drag & Drop doesn't work in IE10

### ISSUE THREAD

**Issue by lorenzulrich** [clauderic/react-sortable-hoc#125]
Sorting by Drag & Drop doesn't work in IE10 and below. It complains about `forEach` which is not available for `clonedFields`. 

![image](https://cloud.githubusercontent.com/assets/1816023/22152098/8e3fa328-df21-11e6-99b6-75dcc9e19781.png)

**Comment by clauderic** [comment]
Hey @lorenzulrich, thanks for reporting this!

This slipped by in the last release, and is caused by the fact that `querySelectorAll` returns a NodeList, which doesn't have the `forEach` method in a lot of browsers (see https://github.com/clauderic/react-sortable-hoc/commit/0b52d14ed5297495d86038dcde5ab18f6aab2b20). 

Just released `0.4.9` with a fix, sorry about that!

**Comment by lorenzulrich** [comment]
Thanks a lot for the quick response. I updated and everything is working now!
