### ISSUE TITLE
Cannot read property 'displayName' of undefined when using SortableElement(defaultHeaderRenderer)

### ISSUE THREAD

**Issue by szabolcsx** [clauderic/react-sortable-hoc#164]
Hi,

I'm trying to implement column header reordering with react-sortable-hoc and react-virtualized.

My idea was to wrap the defaultHeaderRenderer in SortableElement, but after declaring the following, I get the displayName undefined error:
``` TSX
const SortableHeaderRenderer = SortableElement(defaultHeaderRenderer);
```

Did anyone had this issue?

**Comment by clauderic** [comment]
Yeah, I don't think you can do that, since `defaultHeaderRenderer` is being invoked as a function (https://github.com/bvaughn/react-virtualized/blob/eab6b24296f50708a62521982a94d67188fc3a8d/source/Table/Table.js#L403), whereas `SortableElement` returns a component.

Having said that, you can probably create your own `headerRenderer` function that looks something along the lines of:

```js
function headerRenderer(...args) {
  return (
    <SortableItem>
      {defaultHeaderRenderer(...args)}
    </SortableItem>
  );
}
```
