### ISSUE TITLE
[Feature] Add custom sortable helper renderer

### ISSUE THREAD

**Issue by clauderic** [clauderic/react-sortable-hoc#169]
Currently, the sortable helper is being created by cloning the node that a user drags. In the future, it would be great to be able to provide a custom sortable helper renderer to handle use cases such as #50

**Comment by sarah-appsheet** [comment]
+1

My use case is that I'm converting a larger web app to React, one tab at a time. I have to keep the React styles separate from the older non-React styles so they don't interfere - plus I'm using LESS, which encourages nested styles. Since sortable helpers are appended to <body> instead of the parent element, I have to write some clunky overwrite styles so make sure the sortable helpers are styled the same as the original elements.

Or perhaps I've missed another way to handle this kind of situation? Otherwise this library is very easy to integrate with my existing components, and it generally lovely!

**Comment by stevenfabre** [comment]
Agreed. I need to allow users to select and re-order multiple elements.

**Comment by clauderic** [comment]
Update, this is possible using the `updateBeforeSortStart` prop, which lets you update the render output of your component before sorting begins. This can be used to update the render output of the element that is about to be sorted, or to enable re-ordering multiple elements, as shown in this example: https://github.com/clauderic/react-sortable-hoc/tree/master/src/.stories/grouping-items

<img src="https://user-images.githubusercontent.com/1416436/54495093-437d2200-48b7-11e9-885b-05e64c554615.gif" width="400" />

**Comment by mtztkt** [comment]
@clauderic Why did you add an example link for your demo instead of screen recording?
