### ISSUE TITLE
Right Click triggers sort

### ISSUE THREAD

**Issue by natew** [clauderic/react-sortable-hoc#256]
At least for me, even when trying to stopPropagation on the contextmenu event it starts dragging the element. Not sure if contextmenu clicks also trigger normal click, and if that is true, how to disable the second regular event from firing.

**Comment by clauderic** [comment]
Hmm, that shouldn't be the case. See https://github.com/clauderic/react-sortable-hoc/blob/master/src/SortableContainer/index.js#L141

Try adding a `mousedown` event listener in your browser and seeing which `event.button` is returned when you hit the right click 🤔

**Comment by adrianhelvik** [comment]
Same issue here. event.button is 0. Using chrome on an iMac.

**Comment by nessup** [comment]
Also having this issue. I figured it it depends on your mouse input device and how you're using it. I am now using the below to detect right clicks. YMMV, I only needed this to be fixed on macOS, highly recommend testing this on more platforms and devices before you add to your own codebase.

```js
const isRightClick =
  e =>
    (e.buttons === 1 && e.ctrlKey === true) // macOS trackpad
    || (e.buttons === 2 && e.button === 2); // Regular mouse or macOS double-finger tap
```

**Comment by quanglam2807** [comment]
I confirm this bug still exists. 
![ezgif com-optimize](https://user-images.githubusercontent.com/1548835/69013558-d1c60e00-0946-11ea-9510-4e08f837d2c1.gif)

It only happens if you use macOS trackpad CTRL + click (https://www.macworld.co.uk/how-to/mac/right-click-3610351/). The lib works normally with two-finger tap right-click.
