### ISSUE TITLE
cannot auto scroll on Ios 11, neither Safari nor Chrome

### ISSUE THREAD

**Issue by edwardfhsiao** [clauderic/react-sortable-hoc#304]
cannot drag Item0 to Item49 on ios browser neither safari nor chrome in your basic usage example.
![image](https://user-images.githubusercontent.com/11728228/32262902-36f34994-bea5-11e7-9299-3f65d498633d.png)

If I use ``` useWindowAsScrollContainer={true} ``` in my code, it can be dragged to the bottom, however, the animation movement distance wronged。

and it is unable to move up if scrolled to the end of the page

![image](https://user-images.githubusercontent.com/11728228/32262781-9fccf3d0-bea4-11e7-831b-ddddd7e6ef59.png)

**Comment by isualize** [comment]
Ive got the same issue on horizontal scroll...

**Comment by RahulDole** [comment]
@clauderic The auto scroll on dragging of a row doesn't work for me at all (just checked in chrome) in my own application. I don't know what's missing. Could it be a css issue or something wrong in the way the component is being used?

**Comment by apennell** [comment]
I'm experiencing this issue as well, particularly in Chrome. I tried setting `useWindowAsScrollContainer`, which didn't work, but I also don't think I should use it anyway because my container is in a modal. Isn't it supposed to automatically selected the `SortableElement`'s parent `SortableContainer`?

 Scrolling seems to be working in Safari, although it highlights all the rows it passes by!
![screen shot 2018-04-10 at 11 10 40 am 2](https://user-images.githubusercontent.com/11039888/38575471-56eb5960-3cb0-11e8-8f23-27f9e5b2e5e9.png)

**Comment by clauderic** [comment]
`useWindowAsScrollContainer ` was fixed in `0.7.0` thanks to #306, if you still experience issues with this, feel free to reopen
