### ISSUE TITLE
Feature Idea: hierarchical dropping

### ISSUE THREAD

**Issue by jfrolich** [clauderic/react-sortable-hoc#347]
I am thinking about a feature in my product, that needs "hierarchical dropping" (sorry couldn't find a better name).

If you drop (sufficiently) *over* an item, it will have the result that the item will be dropped in that item (like dropping a file on a folder).

Is there anyone also interested in that feature as well? Or does anyone have an idea how to accomplish this without changing the library? Happy to hear your thoughts!

**Comment by escobar5** [comment]
I've found this library: https://github.com/primetwig/react-nestable
Not as sexy as this one, but handles hierarchical dropping

**Comment by paulmichaelxd** [comment]
Sorry to jump in here a bit late, but I'd also recommend this library: https://github.com/atlassian/react-beautiful-dnd

It's pretty sexy (they were pretentious enough to add "beautiful" to the repo name, soo....). But it looks like it handles "hierarchical dropping". In the example you can have items move between groups but also reorder those groups. That feature seems like it would satisfy your requirement.

And it's supported by Atlassian, so won't go away any time soon! I still like this repo because the API is much easier to use for simple use cases, but if you need something more complex, then check out react-beautiful-dnd!

**Comment by clauderic** [comment]
This isn't something I'm planning on supporting in the future, check out the libraries mentioned above if you're looking for this type of feature.
