### ISSUE TITLE
how to prevent items from leaving the container in the Grid type list

### ISSUE THREAD

**Issue by gantit** [clauderic/react-sortable-hoc#520]
![Captura de pantalla 2019-04-02 a las 15 21 31](https://user-images.githubusercontent.com/3631074/55408320-1344ad00-5560-11e9-9dfa-838597885413.png)
When an element of a row is moved to an upper one, get a overflow

one example https://codesandbox.io/embed/0nnq0kv2l

**Comment by TrejGun** [comment]
Hi mate, your example looks fine
But i know what you are talking about because was figthing same issue for 4 ours yesterday ans was about to create an issue about that when found this one

so for me the problem is seen only on certain conditions, when parent has `overflowX: "hidden"`
here is my code https://codesandbox.io/s/w68jykzw58 you can fix it by removing `overflowX: "hidden"` from the wrapper

**Comment by gantit** [comment]
@TrejGun thank you very much with your change has been resolved

**Comment by TrejGun** [comment]
@gantit good to know
