### ISSUE TITLE
tile position calculation is broken

### ISSUE THREAD

**Issue by TrejGun** [clauderic/react-sortable-hoc#523]
from #520 

![image](https://user-images.githubusercontent.com/185285/55752509-e5280700-5a50-11e9-9843-503453e738a5.png)
When an element of a row is moved to an upper one, get a overflow

the problem is seen only on certain conditions.
here is my code https://codesandbox.io/s/w68jykzw58 showing the bug you can fix it by removing overflowX: "hidden" from the wrapper

**Comment by kurtnovack** [comment]
I have a parent container that needs overflow: auto and the same issue happens.

**Comment by crapthings** [comment]
https://streamable.com/rmp97

**Comment by crapthings** [comment]
okay its something like this

https://github.com/atlassian/react-beautiful-dnd/issues/352

grid layout

```js
const SortableList = SortableContainer(({items}) => {
  return (
      <div className='page-grid'>
        {items.map((value, index) => (
          <SortableItem key={`item-${index}`} index={index} value={value} />
        ))}
      </div>
  )
})
```

```stylus
.page-grid
  flex 1
  display grid
  grid-template-columns: 1fr 1fr 1fr 1fr
  grid-gap 32px
  padding 32px
```

**Comment by knarkunas** [comment]
@crapthings - when drag occurs, it adds `translate3d(AAApx, BBBpx, CCCpx)` where `AAA` is your grid element width. What happens is that when calculating how much it should add to `transform`, it does not account for `grid-gap`. I've found that it can be fixed by adding `padding` inside your grid element instead of convenient `grid-gap`.

![Screenshot 2019-07-19 at 07 46 36](https://user-images.githubusercontent.com/37063113/61510435-82ed8380-a9fb-11e9-8b83-21d611b245d0.png)

Same happened to me 😢

**Comment by superdc** [comment]
> I have a parent container that needs overflow: auto and the same issue happens.

I have the same problem, how to fix it? Help wanted

**Comment by knarkunas** [comment]
@superdc use this for guidance: https://github.com/clauderic/react-sortable-hoc/issues/577

Or use version 1.7.1 as a quick fix. Just let's hope later versions did not add what you might need.
