### ISSUE TITLE
how to make a sortable component that swap position instead of reorder

### ISSUE THREAD

**Issue by blumenkranzyn** [clauderic/react-sortable-hoc#621]
I have a sortable list of 5 items, which i can drag and drop to reordenate, like the example: https://codesandbox.io/embed/react-sortable-hoc-test-q6jro

when I drag the "item 5" bellow "item 1", the other items are properly reordenate. when you move one item up, the others go down to keep up the list.

But, instead of it, i want to change the 5 for 1, and 1 for 5, and the other items remains intact, and using this react-sortable-hoc component. I have no idea how to do it, its my first time with react.

**Comment by ABouchard55** [comment]
Instead of using `arrayMove`, create a function (or find one, whatever), that will swap your elements.  `array[oldIndex]` becomes `array[newIndex]` and also the opposite.

Obviously, it would work in the result, but the animation while dragging would not reflect it.

https://codesandbox.io/embed/react-sortable-hoc-test-hybe4

**Comment by clauderic** [comment]
As mentioned by @ABouchard55, you can write your own method to sort the array so that the items end up in the desired position `onSortEnd`

**Comment by amnahkhatun** [comment]
I am able to do swap, but can someone help how to handle reordering animation.

**Comment by coderwei99** [comment]
> I am able to do swap, but can someone help how to handle reordering animation.我可以进行交换，但有人可以帮助如何处理重新排序动画。

I have the same problem. Does anyone know how to resolve it
