### ISSUE TITLE
Components with inputs are breaking on firefox only

### ISSUE THREAD

**Issue by tnrich** [clauderic/react-sortable-hoc#81]
Here is a little gif I made comparing using a react-sortable-hoc on firefox and chrome. I first show the strange behavior happening on firefox and then show it working smoothly in chrome:

![asdfasdfasd](https://cloud.githubusercontent.com/assets/2730609/20013605/fda4513e-a270-11e6-940d-d7c7c954e4d6.gif)

In firefox it seems like the drag handle is trying to be dragged as an image into the input box. Do you know of a good way to prevent that? 

Thanks very much for the excellent component! I know I tried about about 10 different react drag and drop solutions before settling on yours :)

P.S. You're also welcome to see this happening live at http://takara.teselagen.com/ if ya want.

**Comment by clauderic** [comment]
Hey @tnrich, first off, thanks for the kind words, always great to hear :)

Is the handle an image by any chance? I ask because it looks to me like the image is being dragged. If that's the case, try adding `user-drag: none; `  to the drag handle in your CSS (or add `draggable="false"` on the image, or set it as a background-image)

Let me know if that does the trick, if not I'll investigate further. Cheers

**Comment by tnrich** [comment]
Hey @clauderic, 
It is indeed an image. I had already tried adding this css: 

```
user-drag: none; 
user-select: none;
-moz-user-select: none;
-webkit-user-drag: none;
-webkit-user-select: none;
-ms-user-select: none;
```
to the image, but adding a onDragStart={function(e){e.preventDefault()}}
attribute finally got the drag to stop. So problem solved! 

Thanks!
