### ISSUE TITLE
Changing height of SortableItem after drag start breaks size calculations

### ISSUE THREAD

**Issue by nervetattoo** [clauderic/react-sortable-hoc#83]
We wanted to shrink the dragged element `onSortStart`, but at that time the height of the element is already read and subsequently used for move coordinate calculations. Is there any thing we can hook into in order to set height _before_ it is read, or do we need to start working on an enhancement to *react-sortable-hoc*?
If element 1 is 500px high and we set it to 50px on sort start, it will displace the following elements 450px too far towards the top of the container.

**Comment by clauderic** [comment]
Hmmm. I haven't given much thought to this scenario, but it is something I'd be willing to support. Not sure what the best approach would be though, because detecting element resize can be tricky.

One way I can think of to solve this in a flexible manner would be by passing in a `getHelperHeight({index, collection, node})` function that returns the height of the element. Thoughts?

If you don't mind getting your hands dirty, I'd be happy to look at any PR that would attempt to solve this :)

**Comment by nervetattoo** [comment]
It is tricky, because we probably want to animate the shrink-effect, so it wouldn't help to detect size after the outer onDragStart. In our specific case we are going from dynamic heights to a fixed height, so it could even be a number prop as configuration. But a configuration function would be great as well. I'm happy to come up with a PR, just thought I would ask you first in case you had already though of it, or had ideas :)

**Comment by furiousOyster** [comment]
@clauderic do you suppose that instead of copying the raw dom node to the base of the body tag, could it make a new react component, using the SortableItem, and just passing in different props to indicate that it is in drag mode ?
That way, it might be possible to allow people to change whatever they like in the dragable component, even whilst it is in flight, and then measurements could be taken of this on the fly element ?
